import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "How Finora collects, uses and protects your data.",
};

export default function PrivacyPage() {
  return (
    <>
      <h1 className="text-3xl font-bold tracking-tight">Privacy Policy</h1>
      <p className="text-sm text-muted-foreground">
        Last updated: 17 July 2026
      </p>

      <p>
        Finora (&quot;we&quot;, &quot;us&quot;) is a personal finance app
        operated by UDAN Technology. This policy explains what we collect, why,
        and the choices you have. By using Finora you agree to this policy.
      </p>

      <h2 className="pt-4 text-xl font-semibold">1. Information we collect</h2>
      <ul className="list-disc space-y-1 pl-6">
        <li>
          <b>Account details:</b> your name, email address and (optionally)
          phone number, profile photo and bio.
        </li>
        <li>
          <b>Financial data you enter:</b> transactions, accounts, budgets,
          loans and investments. This data is created by you, for you.
        </li>
        <li>
          <b>Payment verification:</b> when you upgrade, the name, email, phone
          and payment screenshot you submit so we can verify your payment
          manually.
        </li>
        <li>
          <b>Technical data:</b> standard server logs (such as IP address and
          browser type) generated by our hosting provider.
        </li>
      </ul>

      <h2 className="pt-4 text-xl font-semibold">2. How we use it</h2>
      <ul className="list-disc space-y-1 pl-6">
        <li>To provide the app and show you your own financial data.</li>
        <li>To verify payments and activate premium access (points).</li>
        <li>
          To send you service emails — upgrade confirmations, and EMI or
          investment-maturity reminders you can expect from the features you
          use.
        </li>
        <li>To keep the service secure and prevent abuse.</li>
      </ul>

      <h2 className="pt-4 text-xl font-semibold">3. Where your data lives</h2>
      <p>
        Your data is stored in a PostgreSQL database (Supabase) protected by
        row-level security, so only your authenticated account can read your
        rows. The app is hosted on Vercel. Transactional emails are sent
        through Resend. These providers process data only to run the service.
      </p>

      <h2 className="pt-4 text-xl font-semibold">4. We do not sell your data</h2>
      <p>
        We never sell or rent your personal or financial information to anyone.
        We do not share it with advertisers.
      </p>

      <h2 className="pt-4 text-xl font-semibold">5. Data retention & deletion</h2>
      <p>
        Your data remains as long as your account exists. If your premium credits
        run out, your data is not deleted — it simply becomes view-only until
        you top up. You may request full deletion of your account and data at
        any time by contacting us.
      </p>

      <h2 className="pt-4 text-xl font-semibold">6. Your choices</h2>
      <ul className="list-disc space-y-1 pl-6">
        <li>Edit your profile and preferences at any time in the app.</li>
        <li>Export your transactions and reports to Excel or PDF.</li>
        <li>Request access to, correction of, or deletion of your data.</li>
      </ul>

      <h2 className="pt-4 text-xl font-semibold">7. Contact</h2>
      <p>
        Questions about your privacy? Email{" "}
        <a
          href="mailto:aryanpariyar8463@gmail.com"
          className="font-medium text-primary underline underline-offset-4"
        >
          aryanpariyar8463@gmail.com
        </a>{" "}
        or message us on WhatsApp at{" "}
        <a
          href="https://wa.me/9779848988463"
          className="font-medium text-primary underline underline-offset-4"
        >
          9848988463
        </a>
        .
      </p>
    </>
  );
}
